import { useState } from 'react';
import { Code, Copy, Check, Play, Download } from 'lucide-react';

const REPLICANT_SAMPLE_CODE = `#!/usr/bin/env python3
"""
AUTO-GOD REPLICANTE v5.2
===============================
Generated automatically by Auto-GOD vΩ Core
Timestamp: 2026-09-29T04:12:00Z
Generation: 5
Parent Accuracy: 0.9120
"""

import os
import sys
import json
import time
import datetime
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Embedding, Dense, LSTM, Conv1D, GlobalAveragePooling1D, Input, MultiHeadAttention, LayerNormalization, Dropout

CONFIG = {
    "dataset": "imdb_reviews",
    "vocab_size": 10000,
    "embedding_dim": 128,
    "batch_size": 32,
    "epochs": 3,
    "architecture": [
        ["conv1d", 128, 5],
        ["attention", 4, 64],
        ["lstm", 256, False],
        ["dropout", 0.3]
    ]
}

class ReplicantModel:
    def __init__(self):
        self.vocab_size = CONFIG["vocab_size"]
    
    def build(self):
        inputs = Input(shape=(None,))
        x = Embedding(self.vocab_size, 128)(inputs)
        x = Conv1D(128, 5, activation='relu', padding='same')(x)
        attn = MultiHeadAttention(num_heads=4, key_dim=64)(x, x)
        x = LayerNormalization()(x + attn)
        x = LSTM(256, return_sequences=False)(x)
        x = Dropout(0.3)(x)
        outputs = Dense(1, activation='sigmoid')(x)
        return Model(inputs, outputs)

class ReplicantTrainer:
    def __init__(self):
        self.model = ReplicantModel().build()
    
    def train(self):
        print("🧬 Replicant model training initiated...")
        self.model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
        print("🎯 Replicant training completed successfully with accuracy: 0.9142")

if __name__ == "__main__":
    trainer = ReplicantTrainer()
    trainer.train()
`;

export function ReplicantsView() {
  const [copied, setCopied] = useState(false);
  const [simulating, setSimulating] = useState(false);
  const [consoleOutput, setConsoleOutput] = useState<string[]>([]);

  const handleCopy = () => {
    navigator.clipboard.writeText(REPLICANT_SAMPLE_CODE);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([REPLICANT_SAMPLE_CODE], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'auto_god_replicant.py';
    a.click();
    URL.revokeObjectURL(url);
  };

  const runSimulation = () => {
    setSimulating(true);
    setConsoleOutput(['[INIT] Loading replicant script...', '[TFDS] Downloading imdb_reviews slice (5%)...']);
    
    setTimeout(() => {
      setConsoleOutput(prev => [...prev, '[BUILD] Assembling Conv1D + Attention + LSTM layers...', '[TRAIN] Epoch 1/3 - loss: 0.4210 - acc: 0.8120']);
    }, 800);

    setTimeout(() => {
      setConsoleOutput(prev => [...prev, '[TRAIN] Epoch 2/3 - loss: 0.2840 - acc: 0.8845', '[TRAIN] Epoch 3/3 - loss: 0.1920 - acc: 0.9142']);
    }, 1600);

    setTimeout(() => {
      setConsoleOutput(prev => [...prev, '[SUCCESS] Replicant validation accuracy: 91.42%', '[SAVE] Model persisted to /replicants/BEST_REPLICANT.py']);
      setSimulating(false);
    }, 2400);
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-sm">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-mono mb-2">
            <Code className="w-3.5 h-3.5" />
            <span>Level 3 · Code Synthesizer & Auto-Replication</span>
          </div>
          <h1 className="text-2xl font-bold text-white">Replicant Code Studio</h1>
          <p className="text-xs text-slate-400 mt-1">
            Inspect, execute, and download self-replicating Python scripts generated by Auto-God Omega.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold rounded-xl border border-slate-700 transition-all cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied' : 'Copy Code'}</span>
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold rounded-xl border border-slate-700 transition-all cursor-pointer"
          >
            <Download className="w-4 h-4" />
            <span>Download .py</span>
          </button>
          <button
            onClick={runSimulation}
            disabled={simulating}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-xl shadow-sm transition-all disabled:opacity-50 cursor-pointer"
          >
            <Play className={`w-4 h-4 ${simulating ? 'animate-pulse' : 'fill-current'}`} />
            <span>{simulating ? 'Executing...' : 'Run Replicant'}</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Code Preview */}
        <div className="lg:col-span-2 bg-slate-950 border border-slate-800 rounded-2xl p-6 font-mono text-xs text-slate-300 overflow-hidden shadow-sm">
          <div className="flex items-center justify-between pb-4 border-b border-slate-800 mb-4 text-slate-400">
            <span>auto_god_replicant.py</span>
            <span>Python 3.10</span>
          </div>
          <pre className="overflow-x-auto max-h-[500px] leading-relaxed text-indigo-200">
            {REPLICANT_SAMPLE_CODE}
          </pre>
        </div>

        {/* Execution Terminal */}
        <div className="bg-slate-950 border border-slate-800 rounded-2xl p-6 font-mono text-xs text-slate-300 flex flex-col justify-between shadow-sm">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-slate-800 mb-4 text-slate-400">
              <span>Terminal Output</span>
              <span className={`w-2 h-2 rounded-full ${simulating ? 'bg-amber-400 animate-ping' : 'bg-emerald-400'}`} />
            </div>

            <div className="space-y-2 min-h-[240px] max-h-[350px] overflow-y-auto">
              {consoleOutput.length === 0 ? (
                <div className="text-slate-600 italic">Click "Run Replicant" to test execution stream...</div>
              ) : (
                consoleOutput.map((line, idx) => (
                  <div key={idx} className={line.includes('SUCCESS') ? 'text-emerald-400 font-bold' : line.includes('INIT') ? 'text-indigo-400' : 'text-slate-300'}>
                    {line}
                  </div>
                ))
              )}
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-800 text-[10px] text-slate-500 flex items-center justify-between">
            <span>Isolation: Subprocess</span>
            <span>Timeout: 600s</span>
          </div>
        </div>
      </div>
    </div>
  );
}
